name: publish images

on:
  push:
    branches: master

jobs:
  publish_images:
    runs-on: ubuntu-latest
    name: Publish Docker images to Dockerhub
    steps:
      - name: Authenticate to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build_images
        run: |
          bash release.sh
